= Vectory

image:https://img.shields.io/gem/v/vectory.svg["Gem Version", link="https://rubygems.org/gems/vectory"]
image:https://github.com/metanorma/vectory/actions/workflows/rake.yml/badge.svg["rake", link="https://github.com/metanorma/vectory/actions/workflows/rake.yml"]
image:https://codeclimate.com/github/metanorma/vectory/badges/gpa.svg["Code Climate", link="https://codeclimate.com/github/metanorma/vectory"]
image:https://img.shields.io/github/issues-pr-raw/metanorma/vectory.svg["Pull Requests", link="https://github.com/metanorma/vectory/pulls"]
image:https://img.shields.io/github/commits-since/metanorma/vectory/latest.svg["Commits since latest",link="https://github.com/metanorma/vectory/releases"]

== Purpose

Vectory is a Ruby gem that performs pairwise vector image conversions for common
vector image formats (EPS, PS, EMF, SVG).

[quote]
____
Vectory shall give you a glorious vectory over EPS files.
____


== Installation

=== Prerequisites

Vectory relies on the following software to be installed:

* https://github.com/metanorma/emf2svg-ruby[emf2svg-ruby]
* https://inkscape.org[Inkscape]
* https://www.ghostscript.com/[Ghostscript]


=== Gem install

[source,ruby]
----
gem install vectory
----

Or include it in your gemspec.


== Usage

[source,sh]
----
$ vectory [-o {output-file-name}] -f {format} {input-file-name}
----

Where,

`format`:: the desired output format (one of: `svg`, `eps`, `ps`, `emf`)
`input-file-name`:: file path to the input file
`output-file-name`:: file path to the desired output file (with the file extension)


=== Using the Ruby library

Some examples:

Take EMF as a path to a file and return SVG as a string:

[source,ruby]
----
path = "path/to/file.emf"
Vectory::Emf.from_path(path).to_svg.content
----

Take SVG as a datauri and return EMF as a datauri:

[source,ruby]
----
# NOTE: datauri is shortened for readability
datauri = "data:image/svg+xml;charset=utf-8;base64,PHN2ZyB4bWxucz0iaHR0 ... GRkYiLz48L3N2Zz4="
Vectory::Svg.from_datauri(datauri).to_emf.datauri
----

Take EPS as a string and return EMF as a path to a file:

[source,ruby]
----
# NOTE: content is shortened for readability
content = "%!PS-Adobe-3.0 EPSF-3.0\n ... %%Trailer"
Vectory::Eps.from_content(content).to_emf.write.path
----

==== What is supported?

All interactions are done around the `Vectory::Image` object. Concrete vectory
classes are descendants of it:

[source,ruby]
----
Vectory::Eps < Image
Vectory::Ps < Image
Vectory::Emf < Image
Vectory::Svg < Image
----

There are several ways of creating an Image object:

[source,ruby]
----
Vectory::Eps.from_path
Vectory::Eps.from_content
Vectory::Eps.from_datauri
----

Converting to other formats:

[source,ruby]
----
Vectory::Eps.from_content(content).to_ps
Vectory::Eps.from_content(content).to_emf
Vectory::Eps.from_content(content).to_svg
----

Several ways of getting a content of an object:

[source,ruby]
----
Vectory::Eps.from_content(content).to_svg.content
Vectory::Eps.from_content(content).to_svg.datauri
Vectory::Eps.from_content(content).to_svg.write.path
----

== Contributing

Bug reports and pull requests are welcome on GitHub at:

* https://github.com/metanorma/vectory
